---
#install Ansible packages for Azure
- name: ensure a list of pre-requisite packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
#    - check-update 
    - gcc 
    - libffi-devel 
    - python-devel 
    - openssl-devel 
    - epel-release
    - python-pip 
    - python-wheel 
