---
 - name: Create VM
   azure_rm_virtualmachine:
     resource_group: "{{ resource_group_name }}"
     name: "{{ vm_name }}"
     vm_size: Standard_DS1_v2
     admin_username:  "{{ admin_user }}"
     ssh_password_enabled: false
     ssh_public_keys:
       - path: "{{ key_path }}" 
         key_data: "{{ key }}" 
     network_interfaces: myNIC
     image:
       offer: CentOS
       publisher: OpenLogic
       sku: '7.5'
       version: latest

