- name: Power off Azure VM
  hosts: localhost
  connection: local

  tasks:
    - name: Power Off
      azure_rm_virtualmachine:
        resource_group: InfraAutomationPOC
        name: myVM
        started: no

