---
 - name: Create public IP address
   azure_rm_publicipaddress:
     resource_group: "{{ resource_group_name }}"
     allocation_method: Static
     name: "{{ public_ip_name }}"
   register: output_ip_address

