---
 - name: Create public IP address
   azure_rm_publicipaddress:
     resource_group: "{{ resource_group_name }}"
     allocation_method: Static
     name: "{{ public_ip_name }}"
   register: output_ip_address

# - name: Dump public IP for VM which will be created
#   debug:
#     msg: "The public IP is {{ output_ip_address.state.ip_address }}."

 - name: Create Network Security Group that allows inbound traffic 
   azure_rm_securitygroup:
     resource_group: "{{ resource_group_name }}"
     name: "{{ nsg_name }}" 
     rules:
       - name: SSH 
         protocol: Tcp
         destination_port_range: 22
         access: Allow
         priority: 1000
         direction: Inbound
       - name: TCP443 
         protocol: Tcp
         destination_port_range: 443
         access: Allow
         priority: 1100
         direction: Inbound
       - name: TCP943 
         protocol: Tcp
         destination_port_range: 943
         access: Allow
         priority: 1200
         direction: Inbound
       - name: UDP1194 
         protocol: Tcp
         destination_port_range: 1194
         access: Allow
         priority: 1300
         direction: Inbound

 - name: Create virtual network inteface card
   azure_rm_networkinterface:
     resource_group: "{{ resource_group_name }}"
     name: "{{ my_nic }}"
     virtual_network: "{{ vnet_name }}"
     subnet: "{{ subnet_name }}"
     public_ip_name: "{{ public_ip_name }}"
     security_group: "{{ nsg_name }}"

 - name: Create VM
   azure_rm_virtualmachine:
     resource_group: "{{ resource_group_name }}"
     name: "{{ vm_name }}"
     vm_size: "{{ vm_size }}"
     admin_username:  "{{ admin_user }}"
     ssh_password_enabled: false
     ssh_public_keys:
       - path: "{{ key_path }}"
         key_data: "{{ key }}"
     network_interfaces: "{{ my_nic }}"
     image:
       offer: UbuntuServer 
       publisher: Canonical
       sku: '16.04.0-LTS'
       version: latest

