---
 - name: Create virtual network inteface card
   azure_rm_networkinterface:
     resource_group: "{{ resource_group_name }}"
     name: myNIC
     virtual_network: "{{ vnet_name }}"
     subnet: "{{ subnet_name }}" 
     public_ip_name: "{{ public_ip_name }}"
     security_group: "{{ nsg_name }}" 

