---

- name: add user tbladmin
  become: yes
  user:
    name: "{{ tsmadmin }}" 
    create_home: yes    
    state: present


- name: Mount /dev/sdb1 to /opt
  become: yes
  shell: |
    echo "{{tsmadmin}} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
#    mount /dev/sdb1 /var/opt

- name: Set Hostname with hostname command
  become: yes
  hostname:
    name: "{{ hostname }}"
  notify:
    - restart hostname
    - restart systemd-logind

- name: Re-gather facts
  action: setup
  when: ansible_hostname != fqdn

- name: Build hosts file (backups will be made)
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }} {{ fqdn }} {{ hostname }}"
    state: present
    backup: yes
  when: ansible_default_ipv4.address is defined
  become: yes
  notify:
    - restart hostname
    - restart systemd-logind


- name: Check that you can connect (GET) to a Azure Blob and download pkg
  become: true
  uri:
    url: "{{ tabl_server_pkg }}" 
    dest: /tmp

