---
- name: Create resource group
  ignore_errors: yes
  azure_rm_resourcegroup:
    name: "{{ resource_group_name }}" 
    location: "{{ default_location }}"
#    subscription_id: "{{ subscription_id }}"
